flysystem:
    storages:
        aws.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(default::AWS_S3_BUCKET)%'
                prefix: 'documents'

        local.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage'
