export const ETRANSPORT_OPERATION_TYPES = [
  { value: 30, label: 'Transport pe teritoriul national (TTN)' },
  { value: 10, label: 'Achizitie intracomunitara (AIC)' },
  { value: 12, label: 'Operatiuni in sistem lohn (UE) - intrare (LHI)' },
  { value: 14, label: 'Stocuri la dispozitia clientului - intrare (SCI)' },
  { value: 20, label: 'Livrare intracomunitara (LIC)' },
  { value: 22, label: 'Operatiuni in sistem lohn (UE) - iesire (LHE)' },
  { value: 24, label: 'Stocuri la dispozitia clientului - iesire (SCE)' },
  { value: 40, label: 'Import (IMP)' },
  { value: 50, label: 'Export (EXP)' },
  { value: 60, label: 'Tranzactie intracomunitara - intrare (DIN)' },
  { value: 70, label: 'Tranzactie intracomunitara - iesire (DIE)' },
] as const

export const ETRANSPORT_PURPOSE_CODES_TTN = [
  { value: 101, label: 'Comercializare' },
  { value: 704, label: 'Transfer intre gestiuni' },
  { value: 705, label: 'Bunuri puse la dispozitia clientului' },
  { value: 9901, label: 'Altele' },
] as const

export const ETRANSPORT_COUNTIES = [
  { value: 1, label: 'Alba' },
  { value: 2, label: 'Arad' },
  { value: 3, label: 'Arges' },
  { value: 4, label: 'Bacau' },
  { value: 5, label: 'Bihor' },
  { value: 6, label: 'Bistrita-Nasaud' },
  { value: 7, label: 'Botosani' },
  { value: 8, label: 'Brasov' },
  { value: 9, label: 'Braila' },
  { value: 10, label: 'Buzau' },
  { value: 11, label: 'Caras-Severin' },
  { value: 12, label: 'Cluj' },
  { value: 13, label: 'Constanta' },
  { value: 14, label: 'Covasna' },
  { value: 15, label: 'Dambovita' },
  { value: 16, label: 'Dolj' },
  { value: 17, label: 'Galati' },
  { value: 18, label: 'Gorj' },
  { value: 19, label: 'Harghita' },
  { value: 20, label: 'Hunedoara' },
  { value: 21, label: 'Ialomita' },
  { value: 22, label: 'Iasi' },
  { value: 23, label: 'Ilfov' },
  { value: 24, label: 'Maramures' },
  { value: 25, label: 'Mehedinti' },
  { value: 26, label: 'Mures' },
  { value: 27, label: 'Neamt' },
  { value: 28, label: 'Olt' },
  { value: 29, label: 'Prahova' },
  { value: 30, label: 'Satu Mare' },
  { value: 31, label: 'Salaj' },
  { value: 32, label: 'Sibiu' },
  { value: 33, label: 'Suceava' },
  { value: 34, label: 'Teleorman' },
  { value: 35, label: 'Timis' },
  { value: 36, label: 'Tulcea' },
  { value: 37, label: 'Vaslui' },
  { value: 38, label: 'Valcea' },
  { value: 39, label: 'Vrancea' },
  { value: 40, label: 'Municipiul Bucuresti' },
  { value: 51, label: 'Calarasi' },
  { value: 52, label: 'Giurgiu' },
] as const

export const ETRANSPORT_COMMON_UOM_CODES = [
  { value: 'KGM', label: 'KGM - Kilogram' },
  { value: 'TNE', label: 'TNE - Tona' },
  { value: 'LTR', label: 'LTR - Litru' },
  { value: 'MTR', label: 'MTR - Metru' },
  { value: 'MTK', label: 'MTK - Metru patrat' },
  { value: 'MTQ', label: 'MTQ - Metru cub' },
  { value: 'XCT', label: 'XCT - Cartoane' },
  { value: 'XBX', label: 'XBX - Cutii' },
  { value: 'XPK', label: 'XPK - Pachete' },
  { value: 'XPX', label: 'XPX - Paleti' },
  { value: 'H87', label: 'H87 - Bucati' },
  { value: 'SET', label: 'SET - Seturi' },
  { value: 'PR', label: 'PR - Perechi' },
  { value: 'XRO', label: 'XRO - Suluri' },
  { value: 'XSA', label: 'XSA - Saci' },
  { value: 'XBA', label: 'XBA - Butoaie' },
] as const

export const ETRANSPORT_STATUS_COLORS: Record<string, string> = {
  uploaded: 'warning',
  ok: 'success',
  nok: 'error',
  validation_failed: 'error',
  upload_failed: 'error',
  pending_timeout: 'warning',
}

export const ETRANSPORT_STATUS_LABELS: Record<string, string> = {
  uploaded: 'Trimis',
  ok: 'Aprobat (UIT)',
  nok: 'Respins',
  validation_failed: 'Eroare validare',
  upload_failed: 'Eroare trimitere',
  pending_timeout: 'Timeout',
}
