#pentru a comenta o linie, cu pastrarea ei dupa salvare, inserati un 'x' la inceputul liniei
#Wed Oct 19 08:55:56 EEST 2011
proxy=auto
defSmartCard=longmai
_D112=optiune standard
tipDeclaratie=D112
urlVersiuni=http://static.anaf.ro/static/10/Anaf/update5/versiuni.xml
#extragereFortataZIP=Dec1|Dec2|...|Decn indica o colectie de documente pt. care se extrage fortat ZIP
extragereFortataZIP=A4200
